CREATE TABLE STUDENT (
    ROLLNO NUMBER PRIMARY KEY,
    NAME VARCHAR2(30),
    AGE NUMBER
);

CREATE TABLE EXAM_RESULT (
    ROLLNO NUMBER,
    EXAM VARCHAR2(30),
    MARKS NUMBER,
    GRADE VARCHAR2(5),
    PRIMARY KEY (ROLLNO, EXAM),
    FOREIGN KEY (ROLLNO) REFERENCES STUDENT(ROLLNO)
);