CREATE TABLE PROJECT (
    PROJECT_NO VARCHAR2(10) PRIMARY KEY,
    CUSTOMERNAME VARCHAR2(50)
);

CREATE TABLE EMPLOYEE_PROJECT (
    EMPNO NUMBER,
    PROJECT_NO VARCHAR2(10),
    NO_OF_DAYS NUMBER,
    PRIMARY KEY (EMPNO, PROJECT_NO),
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);