CREATE TABLE DEPARTMENT (
    DEPTNO NUMBER PRIMARY KEY,
    DNAME VARCHAR2(30),
    LOC VARCHAR2(30)
);

CREATE TABLE EMPLOYEE (
    EMPNO NUMBER PRIMARY KEY,
    ENAME VARCHAR2(30),
    SAL NUMBER,
    DEPTNO NUMBER,
    FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT(DEPTNO)
);